config: configs/pairhead.yaml
output_dir: evo2/contact_map
model_name: evo2_7b
wandb_key: 347615f78afc5589363b8b9428bd47a69b6b6190
wandb_project: 11-781_GenAI_Homework2
run_name: exp-1-pairhead
epochs: 30
pred_head_arch: pairhead
proj_dim: 256
pair_hidden_dim: 256
conv_channels: 64
model: evo2_7b
