run_name: baseline

model: evo2_7b

wandb_key: 347615f78afc5589363b8b9428bd47a69b6b6190
wandb_project: 11-781_GenAI_Homework2
wandb_entity: ltoft-carnegie-mellon-university

epochs: 10
pred_head_arch: baseline